### ISSUE TITLE
可以反复添加同一种颜色

### ISSUE THREAD

**Issue by wiketool** [wbxl2000/zhongguose#1]
## 问题描述

可以反复添加同一种颜色

## 问题复现

对着同一种颜色疯狂点击鼠标...

## 期待效果

添加过的颜色应当被移除或者变灰，禁止重复的添加

## 截图描述
![image](https://user-images.githubusercontent.com/64351271/141434682-620826d4-c57d-4dcc-80a9-3871db89b686.png)

**Comment by wbxl2000** [comment]
非常感谢你的反馈！

对于「是否可以反复添加同一种颜色」这个问题，我认为限制重复添加颜色可能不是一种好的策略，理由主要有：
1. 对于现在的策略（可以添加重复颜色），**在正常使用下**，不会对用户颜色的选取造成困扰，即触发条件只能事用户主动干这件事情，非其他操作的副作用。
2. 如果限制重复添加颜色，可能会限制用户的想象力，目前候选区域其实可以当做用户的调色盘（如果他想的话），比如添加3份蓝色，1份绿色，则配色就想菜鸟裹裹的主题色一样；类似的，还有其他可探索的使用方法。 

目前我打算这样解决：增加「添加重复颜色」的警告 toast，目的是在不限制用户操作的同事，减少误重复添加的可能性。

如你有其他想法，欢迎继续讨论；若表示认同，我将关闭此 issue.
